const tileData = [
    { 
      key: 1,
      img: '../../assets/image/super1.jfif',
      title: 'Breakfast',
      author: 'jill111',
      cols: 2,
      featured: true,
    },
    { key: 2,
      img: '../../assets/image/super2.jfif',
      title: 'Tasty burger',
      author: 'director90',
    },  
    { key: 3,
      img: '../../assets/image/super1.jfif',
      title: 'Camera',
      author: 'Danson67',
    },
    { key: 4,
      img: '../../assets/image/super1.jfif',
      title: 'Morning',
      author: 'fancycrave1',
      featured: true,
    },
    { key: 5,
      img: '../../assets/image/super2.jfif',
      title: 'Hats',
      author: 'Hans',
    },
    { key: 6,
      img: '../../assets/image/super1.jfif',
      title: 'Honey',
      author: 'fancycravel',
    },
    { key: 7,
      img: '../../assets/image/super2.jfif',
      title: 'Vegetables',
      author: 'jill111',
      cols: 2,
    },
    { key: 8,
      img: '../../assets/image/super3.jpg',
      title: 'Water plant',
      author: 'BkrmadtyaKarki',
    },
    { key: 9,
      img: '../../assets/image/super1.jfif',
      title: 'Mushrooms',
      author: 'PublicDomainPictures',
    },
    { key: 10,
      img: '../../assets/image/super2.jfif',
      title: 'Olive oil',
      author: 'congerdesign',
    },
    { key: 11,
      img: '../../assets/image/super1.jfif',
      title: 'Sea star',
      cols: 2,
      author: '821292',
    },
    { key: 12,
      img: '../../assets/image/super3.jpg',
      title: 'Bike',
      author: 'danfador',
    },
  ];
  
  export default tileData;